name: Java with Gradle

on:
  push:
    branches: [1.18-to-1.18.2]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.5.2

      - name: Set up JDK 17
        uses: actions/setup-java@v1.4.4
        with:
          java-version: 17

      - name: Give permissions to Gradle
        run: chmod +x ./gradlew

      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build jar

      - name: Upload a Forge Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: PacketFixerForge
          path: forge/build/libs/**.jar

      - name: Upload a Fabric Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: PacketFixerFabric
          path: fabric/build/libs/**.jar